name: SHFW Bug Report
description: Report a bug to help us improve
title: "SHUT BUG: "
labels: ["bug", "shut"]
body:
  - type: markdown
    attributes:
      value: "Thank you for reporting a bug. Please fill in as much of the template below as you're able."
  - type: dropdown
    id: typeofissue
    attributes:
      label: type of issue
      options:
        - crash
        - UI / UX fix
        - Performance issue
        - Other
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: severity of issue
      options:
        - low (asthetic, minor issue)
        - medium (affects usability but has a workaround)
        - high (major functionality broken, no workaround)
        - ciritcal (app crash, data loss)
    validations:
      required: true
  - type: input
    id: shut_version
    attributes:
      label: SHUT Version
      placeholder: e.g. SHUT 2.3.0 or RCx
    validations:
      required: true
  - type: input
    id: shfw_version
    attributes:
      label: SHFW Version
      placeholder: e.g. SHFW 0.3.7
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Scooter model
      description: Where did the bug occur?
      options:
        - Ninebot G30
        - Ninebot G2
        - Ninebot Es2, Es3, Es4
        - Ninebot E20, E25, E45
        - Xiaomi M365
        - Xiaomi Pro, Pro2, 3
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Description of the Bug
      description: Please describe the issue in as much detail as possible.
      placeholder: "Please describe the issue in as much detail as possible."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide the steps to reproduce the issue, if applicable.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-vs-actual
    attributes:
      label: Expected vs. Actual Behavior
      description: Describe what you expected to happen and what actually happened.
      placeholder: "Expected result... Actual result..."
    validations:
      required: true
  - type: input
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: input
    id: contact-info
    attributes:
      label: Contact Information
      description: Your discord or telegram username in case we need further details.
      placeholder: "Discord or telegram username"
    validations:
      required: false
