name: Label Issue Based on Dropdown Selection

on:
  issues:
    types: [opened, edited]

jobs:
  label-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Apply label based on issue content
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_body = context.payload.issue.body;

            let label = '';

            // Check for specific dropdown selections
            if (issue_body.includes('Product: Utility (SHUT)')) {
              label = 'shut';
            } else if (issue_body.includes('Product: Firmware (SHFW)')) {
              label = 'shfw';
            }

            // Apply the label if a selection was found
            if (label) {
              console.log(`Applying label: ${label}`);
              const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
              await octokit.rest.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels: [label]
              });
            } else {
              console.log('No product selection found in the issue body.');
            }
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
