name: Issue Labeler for Dropdown

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const issueBody = context.payload.issue.body;
            const shfwLabel = 'shfw';
            const shutLabel = 'shut';

            let labelsToAdd = [];

            if (issueBody.includes('"Firmware (SHFW)')) {
              labelsToAdd.push(shfwLabel);
            } else if (issueBody.includes('"Utility (SHUT)"')) {
              labelsToAdd.push(shutLabel);
            }

            if (labelsToAdd.length > 0) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: labelsToAdd
              });
            }
